//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Draft_Current
    {
        public int Id { get; set; }
        public Nullable<int> CurrentPick { get; set; }
        public Nullable<int> CurrentTeamId { get; set; }
        public Nullable<int> CurrentRound { get; set; }
        public Nullable<int> CurrentOverall { get; set; }
    }
}
