//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int ID { get; set; }
        public string Position { get; set; }
        public Nullable<int> Number { get; set; }
        public string PlayerName { get; set; }
        public string Status { get; set; }
        public string Team { get; set; }
    }
}
